version: '3.8'

services:
  app:
    image: ${APP_IMAGE:-ghcr.io/fj-x/simple-vm-deploy:latest}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge